### ISSUE TITLE
Auth Token Cannot Be Renewed With Client

### ISSUE THREAD

**Issue by shamrice** [shamrice/nechat#22]
User must close and reopen app in order for the log in screen to appear which will call a get on auth tokens.

Login screen should be displayed when request is made but token is expired.

**Comment by shamrice** [comment]
Adding example stack trace for reference of token expired while chat with user is up.

`2017-12-18 13:37:24 : EXCEPTION : Server returned HTTP response code: 403 for URL: http://68.194.128.14:5678/nechat-web-service-1.0-SNAPSHOT/messages/history/test_account?after=196
java.io.IOException: Server returned HTTP response code: 403 for URL: http://68.194.128.14:5678/nechat-web-service-1.0-SNAPSHOT/messages/history/test_account?after=196
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
	at io.github.shamrice.neChat.application.rest.client.requests.messages.MessagesRequests.getMessageHistoryAfterMessageId(MessagesRequests.java:113)
	at io.github.shamrice.neChat.application.rest.client.NeChatRestClientImpl.getUnreadMessagesWithUser(NeChatRestClientImpl.java:127)
	at io.github.shamrice.neChat.application.rest.client.NeChatRestClientImpl.getMessagesWithUser(NeChatRestClientImpl.java:86)
	at io.github.shamrice.neChat.application.client.ui.main.MainController.refreshChatTextArea(MainController.java:225)
	at io.github.shamrice.neChat.application.client.ui.main.MainController.access$000(MainController.java:28)
	at io.github.shamrice.neChat.application.client.ui.main.MainController$1.actionPerformed(MainController.java:206)
	at javax.swing.Timer.fireActionPerformed(Timer.java:313)
	at javax.swing.Timer$DoPostEvent.run(Timer.java:245)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)`

**Comment by shamrice** [comment]
Alerts now passed to private method to handle alerting and what to do depending on authentication error. If auth error, will prompt user to log back in. 
Also fixed exiting from app from menu and if they decide not to log back in.
